website/auth.py
from flask import Blueprint,render_template,redirect,url_for,request,session, current_app, jsonify
from website import db, mail
from .models import User, Files, Folders, Loginlog, Loginfailedlog,Signoutlog, Website, Useractivity, Position, Advisory
from werkzeug.security import generate_password_hash, check_password_hash
from .views import uploadpath, websitefolder
from werkzeug.utils import secure_filename
import os
import logging
import random
from datetime import datetime, timedelta
from flask_mail import Message

auth = Blueprint('auth',__name__)

#Email Send
@auth.route('/testingemail')
def test():
    otp = '1234521232'
    name = 'Myko Chan'
    html_path = os.path.join(current_app.root_path,'templates', 'confirmed_email.html')
    with open(html_path, 'r') as file:
        html_content = file.read()

    html_content = html_content.replace('{{ name }}', name)
    msg = Message('Email Successfully Confirmed!', recipients=['sophiagasmen49@gmail.com'])
    msg.html = html_content

    mail.send(msg)
    return 'Email sent successfully!'

@auth.route('/reset-password-teacher', methods=['POST','GET'])
def reset_password_teacher():
    if request.method == 'POST':
        email = request.form['email']
        user = User.query.filter_by(email=email).first()
        if user:
            otp = str(random.randint(100000,999999))
            

            html_path = os.path.join(current_app.root_path,'templates', 'teacher_email_reset_otp_confirmation.html')
            with open(html_path, 'r') as file:
                html_content = file.read()

            html_content = html_content.replace('{{ otp }}', otp)
            msg = Message('Password Reset Request!', recipients=[email])
            msg.html = html_content

            mail.send(msg)
            session['teacher_reset_otp'] = otp
            session['teacher_reset_email_data'] = email
            return render_template('teacherotp.html')
        else:
            msg = 'Email Not Found!'
            return render_template('teacherresetpassword.html', msg=msg)
    return render_template('teacherresetpassword.html')


@auth.route('/teacherotp', methods=['POST','GET'])
def teacherotp():
    if request.method == 'POST':
        otp = request.form['otp']
        otp_session = session.get('teacher_reset_otp')
        if otp == otp_session:
            session.pop('teacher_reset_otp', None)
            print('VErified OTP')
            return render_template('teachernewpassword.html')
        msg = 'Wrong Otp!'
        return render_template('teacherotp.html', msg=msg)
    return redirect(url_for('auth.login'))
    

@auth.route('/teachernewpassword', methods=['POST','GET' ])
def teachernewpassword():
    if request.method == 'POST':
        password = request.form['password']
        confirm = request.form['confirm']
        if password == confirm:
            email = session.get('teacher_reset_email_data')
            teacher = User.query.filter_by(email=email).first()
            hashed = generate_password_hash(password)
            teacher.password = hashed
            db.session.commit()
            session.pop('teacher_reset_email_data', None)
            return redirect(url_for('auth.login'))
        else:
            msg = 'Password Did Not Match!'
            return render_template('teachernewpassword.html', msg=msg)
    return redirect(url_for('auth.login'))




@auth.route('/signup', methods=['POST','GET'])
def signup():
    valididpath = 'website/static/valid_id'
    positions = Position.query.all()
    advisories =  Advisory.query.all()
    otp_expiration_minutes = 5
    
    if request.method == 'POST':
        email = request.form['email']
        fname = request.form['fname']
        lname = request.form['lname']
        password = request.form['password']
        confirm = request.form['confirm']
        position = request.form['position']
        advisory = request.form['advisory']
        valid_id = request.files['valid_id']
        if password == confirm:
            otp = str(random.randint(100000,999999))
            session['otp'] = otp
            session['signup_data'] = {
                'email' : email,
                'fname' : fname,
                'lname' : lname,
                'password' : password,
                'position' : position,
                'advisory' : advisory,
                'valid_id' : valid_id.filename
            }

            # Store the time when the OTP was created as naive
            session['otp_time'] = datetime.now()
            # Store the expiration time for the OTP as naive
            session['otp_expiration'] = (datetime.now() + timedelta(minutes=otp_expiration_minutes))

            #slot for sending otp to email
            
            name = fname + ' ' + lname
            html_path = os.path.join(current_app.root_path,'templates', 'confirmation_email.html')
            with open(html_path, 'r') as file:
                html_content = file.read()

            html_content = html_content.replace('{{ otp }}', otp).replace('{{ name }}', name)
            msg_otp = Message('Email Confirmation!', recipients=[email])
            msg_otp.html = html_content

            mail.send(msg_otp)


            valid_id.save(os.path.join(valididpath,valid_id.filename))
            return render_template('verify_otp.html', email=email, fullname= fname + ' ' + lname)
        else:
            msg = 'Passwords are not identical. Please double-check and retry.'
            return render_template('signup.html', msg=msg)
    return render_template('signup.html', positions=positions, advisories=advisories)


@auth.route('/verify_otp', methods=['POST','GET'])
def verify_otp():

    otp_createdtime = session.get('otp_time')
    expired_time = session.get('otp_expiration')

    if request.method == 'POST':
        otp = request.form['otp']
        stored_otp = session.get('otp')
        stored_data = session.get('signup_data')

        if otp_createdtime:
            expiration_time = expired_time.replace(tzinfo=None)
            if datetime.now() > expiration_time:
                session.pop('otp', None)
                session.pop('signup_data', None)
                session.pop('otp_time', None)
                session.pop('otp_expiration', None)
                return render_template('otp_expired.html')
                    
        if otp == stored_otp:
            hashed_password = generate_password_hash(stored_data['password'])
            mblimit = 0
            status = 'Disallow'
            add_user = User(email=stored_data['email'],fname=stored_data['fname'],
                            lname=stored_data['lname'],password=hashed_password,
                            position=stored_data['position'],advisory=stored_data['advisory'], mblimit=mblimit,status=status, valid_id=stored_data['valid_id'])
            db.session.add(add_user)
            db.session.commit()
            newpath = os.path.join(websitefolder,uploadpath,stored_data['email'])
            os.makedirs(newpath)

            name = stored_data['fname'] + ' ' + stored_data['lname']
            html_path = os.path.join(current_app.root_path,'templates', 'confirmed_email.html')
            with open(html_path, 'r') as file:
                html_content = file.read()

            html_content = html_content.replace('{{ name }}', name)
            msg_confirmed_email = Message('Email Successfully Confirmed!', recipients=[stored_data['email']])
            msg_confirmed_email.html = html_content
            mail.send(msg_confirmed_email)

            session.pop('otp', None)
            session.pop('signup_data', None)
            session.pop('otp_time', None)
            session.pop('otp_expiration', None)
            return render_template('verified_email.html')
        msg = 'Invalid or Expired OTP!'
        return render_template('verify_otp.html', msg=msg,email=stored_data['email'], fullname= stored_data['fname'] + ' ' + stored_data['lname'])
    return redirect(url_for('auth.login'))


@auth.route('/resend_otp', methods=['POST', 'GET'])
def resend_otp():
    data = session.get('otp')
    otp_createdtime = session.get('otp_time')
    expired_time = session.get('otp_expiration')

    if otp_createdtime:
        expiration_time = expired_time.replace(tzinfo=None)
        if datetime.now() > expiration_time:
            session.pop('otp', None)
            session.pop('signup_data', None)
            session.pop('otp_time', None)
            session.pop('otp_expiration', None)
            return render_template('otp_expired.html')
    if data == None:
        return render_template('otp_expired.html')
        
    #slot for sending to email
    print(data)
    stored_data = session.get('signup_data')
    name = stored_data['fname'] + ' ' + stored_data['lname']
    html_path = os.path.join(current_app.root_path,'templates', 'confirmation_email.html')
    with open(html_path, 'r') as file:
        html_content = file.read()

    html_content = html_content.replace('{{ otp }}', data).replace('{{ name }}', name)
    msg_otp = Message('Email Confirmation!', recipients=[stored_data['email']])
    msg_otp.html = html_content
    mail.send(msg_otp)
    
    return jsonify({"message": "OTP sent to your email."}), 200



@auth.route('/login', methods=['POST','GET'])
def login():
    website_detail = Website.query.get(1)
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        user = User.query.filter_by(email=email).first()
        if user and check_password_hash(user.password , password):
            if user.status == 'Disallow':
                msg = 'Please contact the admin to enable your account for login access. Thank you.'

website/templates/actionfolder.html
{% extends 'base.html' %}
{% block content %}
<style>
    @media (max-width: 768px) {
        .card {
            margin: 10px; /* Add some margin around the card */
        }

        .d-flex {
            flex-direction: column; /* Stack the card vertically */
            align-items: center; /* Center the cards */
        }

        .card-body {
            display: flex;
            flex-direction: column; /* Stack buttons vertically */
            align-items: center; /* Center buttons */
        }

        .btn {
            width: 200px; /* Set a fixed width for all buttons */
            margin: 5px 0; /* Add some space between buttons */
        }
    }
</style>

<div class="container mt-5">
    <div class="d-flex justify-content-center">
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-header"><center><b>{{ folders.folder_name }}</b></center></div>
                    <div class="card-body">
                        <a href="/renamefolder/{{ folders.id }}">
                            <button class="btn" style="background-color: lightblue;">Rename</button>
                        </a>
                        <a href="/deletefolder/{{ id }}">
                            <button class="btn" style="background-color: red; color: white;">Delete</button>
                        </a>
                        <a href="/setpasswordfolder/{{ id }}">
                            <button class="btn" style="background-color: rgb(94, 118, 208); color: white;">Set Password</button>
                        </a>
                        <a href="/removefolderpassword/{{ id }}">
                            <button class="btn" style="background-color: rgb(41, 210, 32); color: rgb(33, 47, 37);">Remove Password</button>
                        </a>
                        <a href="">
                            <button class="btn" style="background-color: lightgrey;">Download</button>
                        </a>
                        <a href="/folderinfo/{{ folders.id }}">
                            <button class="btn" style="background-color: gray; color: white;">Info</button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

website/templates/addpositionadvisory.html
{% extends 'baseadmin.html' %}
{% block titleadmin %}Manage Positions and Advisory{% endblock %}

{% block contentadmin %}

<style>
    .container {
     
        max-width: 700px; 
        min-height: 50vh;
        margin: 50px auto; 
        padding: 30px; 
        background-color: #ffffff;
        border-radius: 12px; 
        box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
        font-family: Arial, sans-serif;
    }

    h1 {
        color: #333; 
        margin-bottom: 30px;
        text-align: center;
        text-transform: uppercase;
    }

    table {
        width: 100%;
        margin-top: 20px;
        border-collapse: collapse;
        table-layout: fixed; 
    }

    th, td {
        padding: 15px;
        text-align: center;
        border: 1px solid #dee2e6;
        vertical-align: top;
        word-wrap: break-word; /* Allows long words to be wrapped to the next line */
    }

    th {
        background-color: #007bff; 
        color: white; 
        font-size: 1.2rem;
    }

    td ul {
        list-style-type: none; 
        padding: 0; 
        margin: 0;
    }

    button {
        padding: 12px 20px;
        font-size: 1rem;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s ease, transform 0.2s ease;
    }

    .add-btn {
        background-color: #28a745; 
        color: white; 
    }

    .delete-btn {
        background-color: #dc3545; 
        color: white; 
    }

    button:hover {
        transform: translateY(-2px);
    }

    .actions {
        display: flex;
        justify-content: center;
        margin-top: 20px;
        gap: 5px;
    }

    .warning {
        color: red;
        text-align: center;
        margin-top: 20px;
        font-weight: bold;
    }

    @media (max-width: 600px) {
        h1 {
            font-size: 2rem; 
        }

        button {
            width: 100%;
            font-size: 0.9rem;
        }
    }
    .advisory {
        margin-left: 10%;
    }
</style>

<div class="container">
    <h2>Manage Positions and Advisory</h2>
    <table>
        <thead>
            <tr>
                <th style="width: 50%;">Positions</th> 
                <th style="width: 50%;">Advisory</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <ul>
                        {% for i in positions%}
                        <li>{{ i.name }}</li>
                        {% endfor %}
                    </ul>
                </td>
                <td>
                    <ul>
                        {% for i in advisories %}
                        <li> {{ i.name }}</li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>
        </tbody>
    </table>

    <div class="actions">
        <a href="/addposition">
            <button class="add-btn">Add Position</button>
        </a>
        <a href="/deleteposition">
            <button class="delete-btn">Delete Position</button>
        </a>
        <div class="advisory">
            <a href="/addadvisory">
                <button class="add-btn">Add Advisory</button>
            </a>
            <a href="/deleteadvisory">
                <button class="delete-btn">Delete Advisory</button>
            </a>
        </div>
    </div>

    <div class="warning">
        <strong>Warning:</strong> Deleting will permanently remove all
    </div>

    <div class="actions">
        <a href="/deleteallpositionadvisory">
            <button class="delete-btn">Delete All</button>
        </a>
    </div>
</div>

{% endblock %}

website/templates/adminpasswordotp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OTP Verification</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
            background-color: #ffffff;
            color: #fff;
            font-family: Arial, sans-serif;
        }
        .login-container {
            margin-top: 100px;
            max-width: 400px;
            background-color: #1a1a1a;
            padding: 40px;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);
        }
        .form-control {
            background-color: #2b2b2b;
            border: none;
            color: #fff;
            text-align: center;
        }
        .form-control:focus {
            background-color: #3a3a3a;
            border-color: #555;
        }
        .btn-primary {
            background-color: #fff;
            color: #000;
            border: none;
        }
        .btn-primary:hover {
            background-color: #ccc;
            color: #000;
        }
    </style>
</head>
<body>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-4">
            <div class="login-container text-center">
                <i class="fa-solid fa-3x fa-key mb-2"></i>
                <form action="/otp_verify_admin" method="POST">
                    <p>OTP Verification</p>
                    <div class="form-group">
                        <input type="text" name="otp" class="form-control" placeholder="Enter 6-digit OTP" maxlength="6" required>
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">Verify OTP</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" crossorigin="anonymous"></script>

</body>
</html>

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <style>
        .time-box {
            display: flex;
            align-items: center;
            margin-right: 1rem;
        }
        .time-box i {
            margin-right: 0.5rem;
        }
        @media (max-width: 700px){
            .dashboard, .message{
                display: none;
            }
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="border-bottom: 1px solid rgb(134, 132, 132);">
        <a class="navbar-brand" href="/">{{mykochangwapo}}</a>
        <div class="time-box" id="timeBox">
            <!-- Icons and time will be injected by JavaScript -->
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/Teachers">Teachers</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/files">Files</a>
                </li>
                <li class="nav-item dashboard">
                    <a class="nav-link" href="/dashboard">Dashboard</a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="/announcement" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Announcement
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="/announcement">View</a>
                        {% if mykochangwapo_userpos == 'Principal' %}
                        <a class="dropdown-item" href="/new_announcement">Send</a>
                        {% else %}
                        {% endif %}
                    </div>
                </li>
                <li class="nav-item message">
                    <a class="nav-link" href="/messages/1">Messages</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="/profile">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/signout">Logout</a>
                </li>            
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" crossorigin="anonymous"></script>
    <script>
       
        function updateTime() {
            const now = new Date();
            let hours = now.getHours();
            const minutes = now.getMinutes().toString().padStart(2, '0'); 
            const seconds = now.getSeconds().toString().padStart(2, '0');
            const ampm = hours >= 12 ? 'PM' : 'AM';
            const greeting = hours >= 12 ? (hours >= 17 ? 'Good Evening' : 'Good Afternoon') : 'Good Morning';
            
            hours = hours % 12;
            hours = hours ? hours : 12; 
            const hoursString = hours.toString().padStart(2, '0'); 

            const timeString = `${hoursString}:${minutes}:${seconds} ${ampm}`;
           
            const icon = ampm === 'PM' ? 'fas fa-sun' : 'fas fa-moon';

           
            document.getElementById('timeBox').innerHTML = `<i class="${icon}"></i> ${greeting}: ${timeString}`;
        }

      
        updateTime();
        setInterval(updateTime, 1000);
        document.getElementById('navbarDropdown').addEventListener('click', function (e) {
  
            if (e.target.classList.contains('dropdown-toggle') && e.offsetX > this.offsetWidth - 30) {
                e.preventDefault(); 
            } else {
                window.location.href = '/announcement'; 
            }
        });
    </script>
</body>
</html>

website/templates/changepassword.html
{% extends 'base.html' %}
{% block content %}

<div class="container d-flex justify-content-center align-items-center mt-5">
    <div class="card shadow-lg border-0" style="max-width: 400px; width: 100%;">
        <div class="card-header bg-primary text-white text-center py-4">
            <h4 class="font-weight-bold mb-0"><i class="fas fa-lock"></i> Change Password</h4>
        </div>
        <div class="card-body py-4">
            <form action="/change_password" method="POST">
                <div class="form-group mb-4">
                    <label for="password" class="form-label"><i class="fas fa-key"></i> New Password</label>
                    <input type="password" name="password" id="password" class="form-control" placeholder="Enter new password" required>
                </div>

                <div class="form-group mb-4">
                    <label for="confirm_password" class="form-label"><i class="fas fa-key"></i> Confirm Password</label>
                    <input type="password" name="confirm_password" id="confirm_password" class="form-control" placeholder="Confirm new password" required>
                </div>

                <div class="text-center">
                    <button type="submit" class="btn btn-danger btn-lg">
                        <i class="fas fa-check-circle"></i> Change Password
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

website/templates/changeposition.html
{% extends 'base.html' %}


{% block content %}
<div class="container d-flex justify-content-around align-items-center mt-5">
    <div class="jumbotron jumbotron-custom">
        <h2>Position</h2>
        <br>
        <div class="form-group mt-2">
            <h6>Change to:</h6>
            <form action="{{ url_for('auth.changeposition')}}" METHOD="POST">
                <select name="position" id="" class="form-control">
                    <option value="Teacher 1">Teacher I</option>
                    <option value="Teacher 2">Teacher II</option>
                    <option value="Teacher 3">Teacher III</option>
                    <option value="Master Teacher">Master Teacher</option>
                    <option value="Head Teacher">Head Teacher</option>
                    <option value="Principal">Principal</option>
                    {% for i in positions %}
                    <option value="{{i.name}}"> {{ i.name }}</option>
                    {% endfor %}
                </select>
                <br/>
                <div class="text-center">
                <button type="submit" class="btn btn-danger">Change</button>
                </div>
            </form>
            
        </div>

    </div>


</div>



{% endblock %}

website/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <style>
        body {
            height: 100vh;
            margin: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            background: linear-gradient(135deg, #8e6ee4, #88d3ce);
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        }
        .container {
            margin-top: 3%;
            max-width: 500px;
        }
        .jumbotron-custom {
            padding: 2rem;
            border-radius: 1rem;
            background: #ffffff;
            text-align: center;
        }
        .jumbotron-custom img {
            width: 100px;
            height: 100px;
            border-radius: 50%;
            margin-bottom: 1rem;
        }
        .form-group label {
            font-size: 0.875rem;
            font-weight: 600;
        }
        .form-control {
            border-radius: 0.25rem;
            box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1);
            border-color: #ced4da;
        }
        .btn {
            border-radius: 0.25rem;
            font-weight: 600;
            padding: 0.75rem;
        }
        .btn-primary {
            background-color: #6e45e2;
            border: none;
        }
        .btn-primary:hover {
            background-color: #5a33c5;
        }
        .btn-secondary {
            background-color: #9eb0c2;
            border: none;
        }
        .btn-secondary:hover {
            background-color: #e2e6ea;
        }
        .btn-icon {
            margin-right: 0.5rem;
        }
        
    </style>
</head>
<body>
    
    <div class="container">
        <div class="jumbotron jumbotron-custom">
            <img src="{{ url_for('static', filename='img/' ~ website_detail.logo) }}" alt="{{ website_detail.name }}">
            <h2 class="font-weight-bold mb-3">{{ website_detail.name }}</h2>
            
            <form action="/login" method="POST">
                <div class="form-group">
                    <label for="email"><i class="fas fa-envelope btn-icon"></i> Email</label>
                    <input type="email" name="email" id="email" class="form-control" placeholder="someone@gmail.com" required>
                </div>
                <div class="form-group">
                    <label for="password"><i class="fas fa-lock btn-icon"></i> Password</label>
                    <input type="password" name="password" id="password" class="form-control" placeholder="**********" required>
                    <br>
                    <a href="/reset-password-teacher" style="color: red;">
                    <h6>Reset Password</h6>
                    </a>
                </div>
              
                <p class="text-danger text-center">{{msg}}</p>
                {% block error_login %} {% endblock %}
           
                <button type="submit" class="btn btn-primary btn-block"><i class="fas fa-sign-in-alt btn-icon"></i> Log In</button>
            </form>
            
            <div class="mt-3">
                <a href="{{ url_for('auth.signup') }}" class="btn btn-secondary btn-block"><i class="fas fa-user-plus btn-icon"></i> Sign Up</a>
            </div>
            
        </div>
    </div>

</body>
</html>